#!/bin/bash

# exit on any error
set -e

echo Cleaning…
rm -rf dist

echo Compiling JS…
npx babel \
  --ignore "src/**/*.test.ts","src/**/*.d.ts","**/*/__example-files__/**/*"\
  --source-maps true \
  --extensions .ts,.js \
  --out-dir dist \
  ./src

echo Compling types…
npx tsc

echo Copying files…
cp ./src/index.d.ts ./dist
